import { mkdir, readFile, writeFile } from "node:fs/promises";

const artifactPath = "artifacts/contracts/PropertyToken.sol/PropertyToken.json";
const outputPath = "abi/PropertyToken.json";
const frontendOutputPath = "src/contracts/generated/propertyTokenAbi.ts";
const artifact = JSON.parse(await readFile(artifactPath, "utf8"));

await mkdir("abi", { recursive: true });
await writeFile(
  outputPath,
  `${JSON.stringify(
    {
      contractName: artifact.contractName,
      sourceName: artifact.sourceName,
      abi: artifact.abi,
    },
    null,
    2,
  )}\n`,
  "utf8",
);

await mkdir("src/contracts/generated", { recursive: true });
await writeFile(
  frontendOutputPath,
  `// Generated by scripts/export-abi.mjs. Do not edit manually.\nexport const propertyTokenAbi = ${JSON.stringify(
    artifact.abi,
    null,
    2,
  )} as const\n`,
  "utf8",
);

console.log(`Exported ${outputPath} and ${frontendOutputPath}`);
